DROP TABLE ;
go;

CREATE TABLE Consignors (SignorID INT IDENTITY, Name VARCHAR(100) NOT NULL, Address VARCHAR(300), City VARCHAR(30) NOT NULL,
CONSTRAINT pk_Signor_ID PRIMARY KEY(SignorID), CONSTRAINT uk_Signor_Name UNIQUE(Name))

CREATE TABLE Consignees (SigneeID INT IDENTITY, Name VARCHAR(100) NOT NULL, Address VARCHAR(300), City VARCHAR(30) NOT NULL,
CONSTRAINT pk_Signee_ID PRIMARY KEY(SigneeID), CONSTRAINT uk_Signee_Name UNIQUE(Name))

CREATE TABLE CatCharges(CID INT, Name VARCHAR(50), CONSTRAINT pk_CatC_CID PRIMARY KEY(CID), CONSTRAINT uk_CatC_Name UNIQUE(Name))

CREATE TABLE AppCharges(CNo INT, CID INT, Charges MONEY, CONSTRAINT pk_AppC_CNo PRIMARY KEY(CNo, CID),
CONSTRAINT fk_AppC_CNo FOREIGN KEY(CNo) REFERENCES Consignments(CNo), CONSTRAINT fk_AppC_CID FOREIGN KEY(CID) REFERENCES CatCharges(CID))

CREATE TABLE CatDistance (DistanceID INT IDENTITY, DFrom CHAR(30) NOT NULL, DTo CHAR(30), Charges MONEY NOT NULL,
CONSTRAINT pk_CatDist_ID PRIMARY KEY(DistanceID))

CREATE TABLE CatMP (MultiPoints NUMERIC(1) DEFAULT(1), Charges MONEY NOT NULL, CONSTRAINT pk_CatMP_MP PRIMARY KEY(MultiPoints))

CREATE TABLE CatHalting (SignorID NCHAR(100), Charges MONEY NOT NULL, CONSTRAINT pk_CatHalt_Cons PRIMARY KEY(Consignor))

CREATE TABLE CatUnloading (SignorID NCHAR(100), Charges MONEY NOT NULL, CONSTRAINT pk_CatUnload_Cons PRIMARY KEY(Consignor))

CREATE TABLE CatCheckpost (SignorID NCHAR(100), Charges MONEY NOT NULL, CONSTRAINT pk_CatCheck_Cons PRIMARY KEY(Consignor))

CREATE TABLE CatLoading (SignorID NCHAR(100), Charges MONEY NOT NULL, CONSTRAINT pk_CatLoad_Cons PRIMARY KEY(Consignor))

CREATE TABLE CatStatical (SignorID NCHAR(100), Charges MONEY NOT NULL, CONSTRAINT pk_CatStat_Cons PRIMARY KEY(Consignor))
