--prepare database
use DbLocality
truncate table Countries
drop table Countries
go

--generating table
create table Countries(CountryID int identity, Country nvarchar(100) NOT NULL, constraint pkCID_Countries PRIMARY KEY(CountryID),
constraint ukCountry_Countries unique(Country))
go

--	inserting Countries
insert Countries values('Afghanistan')
insert Countries values('Argentina')
insert Countries values('Australia')
insert Countries values('Bahamas')
insert Countries values('Bahrain')
insert Countries values('Bangladesh')
insert Countries values('Belgium')
insert Countries values('Bermuda')
insert Countries values('Bhutan')
insert Countries values('Brazil')
insert Countries values('British Indian Ocean')
insert Countries values('British Virgin Islands')
insert Countries values('Bulgaria')
insert Countries values('Cameroon')
insert Countries values('Canada')
insert Countries values('Central African Republic')
insert Countries values('Chile')
insert Countries values('China')
insert Countries values('Colombia')
insert Countries values('Costa Rica')
insert Countries values('Croatia')
insert Countries values('Cuba')
insert Countries values('Cyprus')
insert Countries values('Czech Republic')
insert Countries values('Denmark')
insert Countries values('Dominican Republic')
insert Countries values('Egypt')
insert Countries values('El Salvador')
insert Countries values('Ethiopia')
insert Countries values('Fiji')
insert Countries values('Finland')
insert Countries values('France')
insert Countries values('Georgia')
insert Countries values('Germany')
insert Countries values('Ghana')
insert Countries values('Greece')
insert Countries values('Greenland')
insert Countries values('Haiti')
insert Countries values('Hong Kong')
insert Countries values('Hungary')
insert Countries values('Iceland')
insert Countries values('India')
insert Countries values('Indonesia')
insert Countries values('Iran')
insert Countries values('Iraq')
insert Countries values('Ireland')
insert Countries values('Israel')
insert Countries values('Italy')
insert Countries values('Jamaica')
insert Countries values('Japan')
insert Countries values('Kazakhstan')
insert Countries values('Kenya')
insert Countries values('Korea')
insert Countries values('Kuwait')
insert Countries values('Lebanon')
insert Countries values('Liberia')
insert Countries values('Libya')
insert Countries values('Macau')
insert Countries values('Madagascar')
insert Countries values('Malaysia')
insert Countries values('Maldives')
insert Countries values('Mauritius')
insert Countries values('Mexico')
insert Countries values('Micronesia')
insert Countries values('Mongolia')
insert Countries values('Myanmar')
insert Countries values('Nepal')
insert Countries values('Netherlands')
insert Countries values('New Zealand')
insert Countries values('Nigeria')
insert Countries values('North Korea')
insert Countries values('Norway')
insert Countries values('Oman')
insert Countries values('Pakistan')
insert Countries values('Panama')
insert Countries values('Peru')
insert Countries values('Philippines')
insert Countries values('Phoenix Islands')
insert Countries values('Poland')
insert Countries values('Portugal')
insert Countries values('Puerto Rico')
insert Countries values('Qatar')
insert Countries values('Reunion')
insert Countries values('Romania')
insert Countries values('Russia')
insert Countries values('Saudi Arabia')
insert Countries values('Serbia')
insert Countries values('Sierra Leone')
insert Countries values('Singapore')
insert Countries values('Soloman Islands')
insert Countries values('Somalia')
insert Countries values('South Africa')
insert Countries values('South Korea')
insert Countries values('Spain')
insert Countries values('Sri Lanka')
insert Countries values('Swaziland')
insert Countries values('Sweden')
insert Countries values('Switzerland')
insert Countries values('Syria')
insert Countries values('Taiwan')
insert Countries values('Thailand')
insert Countries values('Tunisia')
insert Countries values('Turkey')
insert Countries values('Uganda')
insert Countries values('Ukraine')
insert Countries values('United Arab Emirates')
insert Countries values('United Kingdom')
insert Countries values('United States of America')
insert Countries values('Uzbekistan')
insert Countries values('Vatican')
insert Countries values('Venezuela')
insert Countries values('Vietnam')
insert Countries values('Wallis and Futuna Islands')
insert Countries values('Yemen')
insert Countries values('Zambia')
insert Countries values('Zimbabwe')
