--prepare database
use DbLocality
truncate table Cities
drop table Cities
go

--generating table
create table Cities(CityID int identity, City nvarchar(100) NOT NULL, StateID int NOT NULL, constraint pkCID_Cities PRIMARY KEY(CityID),
constraint ukCity_State_States unique(City, StateID), constraint fkSID_Cities_States FOREIGN KEY(StateID) REFERENCES States)

--insert Cities of Uttar Pradesh of India
insert Cities values('Agra', 28)
insert Cities values('Akbarpur', 28)
insert Cities values('Aligarh', 28)
insert Cities values('Allahabad', 28)
insert Cities values('Amroha', 28)
insert Cities values('Auraiya', 28)
insert Cities values('Azamgarh', 28)
insert Cities values('Badaun', 28)
insert Cities values('Baghpat', 28)
insert Cities values('Bahraich', 28)
insert Cities values('Ballia', 28)
insert Cities values('Balrampur', 28)
insert Cities values('Banda', 28)
insert Cities values('Bara banki', 28)
insert Cities values('Bareilly', 28)
insert Cities values('Basti', 28)
insert Cities values('Bela', 28)
insert Cities values('Bhadohi', 28)
insert Cities values('Bulandshahar', 28)
insert Cities values('Deoria', 28)
insert Cities values('Etah', 28)
insert Cities values('Etawah', 28)
insert Cities values('Faizabad', 28)
insert Cities values('Fatehgarh', 28)
insert Cities values('Fatehpur', 28)
insert Cities values('Firozabad', 28)
insert Cities values('Ghaziabad', 28)
insert Cities values('Ghazipur', 28)
insert Cities values('Gonda', 28)
insert Cities values('Gorakhpur', 28)
insert Cities values('Hamirpur', 28)
insert Cities values('Hardoi', 28)
insert Cities values('Haridwar', 28)
insert Cities values('Hathras', 28)
insert Cities values('Jaunpur', 28)
insert Cities values('Jhansi', 28)
insert Cities values('Kanpur', 28)
insert Cities values('Karwi', 28)
insert Cities values('Khalilabad', 28)
insert Cities values('Kheri', 28)
insert Cities values('Lalitpur', 28)
insert Cities values('Lucknow', 28)
insert Cities values('Maharajganj', 28)
insert Cities values('Mahoba', 28)
insert Cities values('Mainpuri', 28)
insert Cities values('Manjhanpur', 28)
insert Cities values('Mathura', 28)
insert Cities values('Mau', 28)
insert Cities values('Meerut', 28)
insert Cities values('Mirzapur', 28)
insert Cities values('Muradabad', 28)
insert Cities values('Muzaffarnagar', 28)
insert Cities values('Noida', 28)
insert Cities values('Orai', 28)
insert Cities values('Padrauna', 28)
insert Cities values('Pilibhit', 28)
insert Cities values('Rae Bareli', 28)
insert Cities values('Rampur', 28)
insert Cities values('Roertsganj', 28)
insert Cities values('Saharanpur', 28)
insert Cities values('Shahjahanpur', 28)
insert Cities values('Sitapur', 28)
insert Cities values('Sonai ka chaurah', 28)
insert Cities values('Sultanpur', 28)
insert Cities values('Udham singh nagar', 28)
insert Cities values('Unnao', 28)
insert Cities values('Varanasi', 28)
