--prepare database
use DbLocality
truncate table Cities
drop table Cities
go

--generating table
create table Cities(CityID int identity, City nvarchar(100) NOT NULL, StateID int NOT NULL, constraint pkCID_Cities PRIMARY KEY(CityID),
constraint ukCity_State_States unique(City, StateID), constraint fkSID_Cities_States FOREIGN KEY(StateID) REFERENCES States)

--insert Cities of Maharashtra of India
insert Cities values('Ahmadnagar', 16)
insert Cities values('Akot', 16)
insert Cities values('Alibag', 16)
insert Cities values('Amgaon', 16)
insert Cities values('Aurangabad', 16)
insert Cities values('Bandra', 16)
insert Cities values('Bhandara', 16)
insert Cities values('Bhiwandi', 16)
insert Cities values('Bhiwapur', 16)
insert Cities values('Bid', 16)
insert Cities values('Chalisgaon', 16)
insert Cities values('Chandrapur', 16)
insert Cities values('Chiplun', 16)
insert Cities values('Daryapur', 16)
insert Cities values('Dharashiv', 16)
insert Cities values('Dombivali', 16)
insert Cities values('Garhchiroli', 16)
insert Cities values('Gondia', 16)
insert Cities values('Hingoli', 16)
insert Cities values('Jalgaon', 16)
insert Cities values('Jalna', 16)
insert Cities values('Jamkhed', 16)
insert Cities values('Jath', 16)
insert Cities values('Junnar', 16)
insert Cities values('Kalyan', 16)
insert Cities values('Kashti', 16)
insert Cities values('Khandala', 16)
insert Cities values('Kolhapur', 16)
insert Cities values('Koyna', 16)
insert Cities values('Kudal', 16)
insert Cities values('Latur', 16)
insert Cities values('Lonavala', 16)
insert Cities values('Loni', 16)
insert Cities values('Madh', 16)
insert Cities values('Mahabaleshwar', 16)
insert Cities values('Malvan', 16)
insert Cities values('Mohol', 16)
insert Cities values('Mumbai', 16)
insert Cities values('Nagpur', 16)
insert Cities values('Nanded', 16)
insert Cities values('Nandurbar', 16)
insert Cities values('Nasik', 16)
insert Cities values('Nawegaon', 16)
insert Cities values('Nevasa', 16)
insert Cities values('Panchgani', 16)
insert Cities values('Panvel', 16)
insert Cities values('Parbhani', 16)
insert Cities values('Pune', 16)
insert Cities values('Rahuri', 16)
insert Cities values('Raigarh', 16)
insert Cities values('Ratnagiri', 16)
insert Cities values('Roha', 16)
insert Cities values('Sangli', 16)
insert Cities values('Satara', 16)
insert Cities values('Solapur', 16)
insert Cities values('Thane', 16)
insert Cities values('Tuljapur', 16)
insert Cities values('Ulhasnagar', 16)
insert Cities values('Vada', 16)
insert Cities values('Vajreshwari', 16)
insert Cities values('Vapi', 16)
insert Cities values('Vengurla', 16)
insert Cities values('Virar', 16)
insert Cities values('Waluj', 16)
insert Cities values('Wardha', 16)
insert Cities values('Washi', 16)
insert Cities values('Washim', 16)
insert Cities values('Yavatmal', 16)
