CREATE TABLE BILLS (
BillNo INT
, BillDate DATE NOT NULL
, PartyId INT NOT NULL
, Total decimal(12,2) NOT NULL
, CONSTRAINT pkBillNo_Bills PRIMARY KEY(BILLNO)
, CONSTRAINT fkPartyId_Bills_Parties FOREIGN KEY(PARTYID) REFERENCES PARTIES(PARTYID)
)